# Generated by Django 5.2 on 2025-11-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=200)),
                ("deskripsi", models.TextField()),
                ("gambar", models.ImageField(upload_to="course_images/")),
                ("tanggal_dibuat", models.DateTimeField(auto_now_add=True)),
                ("tanggal_diperbarui", models.DateTimeField(auto_now=True)),
                ("harga", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_published", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="durasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_durasi", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="is_paid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_price", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_kategori", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_level", models.CharField(max_length=100)),
            ],
        ),
    ]
