# Generated by Django 5.2 on 2025-11-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("tutor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tutor.tutor"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="durasi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.durasi"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_bayar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.is_paid"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="kategori",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.kategori"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.level"
            ),
        ),
    ]
