# Generated by Django 5.2 on 2025-11-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="aboutTutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tentang", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="experienceTutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tahun", models.CharField(max_length=4)),
                ("judul", models.CharField(max_length=200)),
                ("sub_judul", models.CharField(max_length=200)),
                ("deskripsi", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_tutor", models.CharField(max_length=200)),
                ("pengalaman", models.TextField()),
                ("kontak", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("nomor_telepon", models.CharField(max_length=15)),
                ("alamat", models.TextField()),
                (
                    "keahlian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.kategori",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="courseTutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tutor.tutor"
                    ),
                ),
            ],
        ),
    ]
